* Hatenadiarywriter

This is `Hatena diary writer'(http://www.hyuki.com/techinfo/hatena_diary_writer.html) in Ruby.


** Installation

Add this line to your application's Gemfile:

#+BEGIN_SRC ruby
  gem 'hatenadiarywriter'
#+END_SRC

And then execute:

#+BEGIN_EXAMPLE
  $ bundle
#+END_EXAMPLE

Or install it yourself as:

#+BEGIN_EXAMPLE
  $ gem install hatenadiarywriter
#+END_EXAMPLE


** Usage

Basically, please refer original Perl version's page (http://www.hyuki.com/techinfo/hatena_diary_writer.html).

In the following, show differences from original version and additional points.

*** Option

Options got long name.

#+BEGIN_EXAMPLE
  $ rhw --help
  Usage: rhw [options]
      -d, --debug                      Turn on debug mode.
      -t, --trivial                    Turn on `Trivial update' mode.
      -u, --username=ID                Specify Hatena ID.
      -p, --password=PASS              Specify a password.
      -a, --user-agent=NAME            Specify user agent name to access.
      -T, --timeout=SEC                Specify timeout limit seconds.
      -g, --groupname=NAME             Specify group name to post to group-diary.
      -c, --cookie                     Use cookie to access with config value `cookie_file'.
      -f, --file=PATH                  Specify posting file.
      -M, --no-timestamp               Suppress substituting *t* notation.
      -n, --config-file=PATH           Specify a config file.
#+END_EXAMPLE

*** Config item

#+BEGIN_QUOTE
Renamed:
- txt_dir -> =diary_dir=
#+END_QUOTE

#+BEGIN_QUOTE
Added:
- diary_glob :: specify glob pattern for diary files under =diary_dir= (default: "*.txt")
#+END_QUOTE

#+BEGIN_QUOTE
Aliased:
- username       :: alias for =id=
- groupname      :: alias for =g=
- cookie_file    :: alias for =cookie=
- http_proxy     :: alias for =proxy=
- filter_command :: alias for =filter=
- touch_file     :: alias for =touch=
#+END_QUOTE


*** Config file syntax

There is no difference at first glance, "colon-separated format", but actually this program parses config file
as *YAML format*. Accordingly default config file is /config.yml/.

For example, following YAML document has syntax error because YAML format has "alias" notation with '*'
(parser says such as "undefined alias.").

#+BEGIN_SRC yaml
  diary_dir:  ~/diary
  diary_glob: *.txt
#+END_SRC

Correctly, like this:

#+BEGIN_SRC yaml
  diary_dir:  ~/diary
  diary_glob: "*.txt"
#+END_SRC

Needs quotation to specify value is string!

*** Cookie

When original founds =cookie_file= item in config file, turns on =-c= option. But this program requires
*both of* =-c= option and =cookie_file= config to use cookie.


** Development

To install this gem onto your local machine, run
=bundle exec rake install=. To release a new version, update the version
number in =version.rb=, and then run =bundle exec rake release= to
create a git tag for the version, push git commits and tags, and push
the =.gem= file to [[https://rubygems.org][rubygems.org]].


** Contributing

1. Fork it (
   [[https://github.com/[my-github-username]/hatenadiarywriter/fork]] )
2. Create your feature branch (=git checkout -b my-new-feature=)
3. Commit your changes (=git commit -am 'Add some feature'=)
4. Push to the branch (=git push origin my-new-feature=)
5. Create a new Pull Request


